#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuckyIsland.API.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DataSourceConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DBSportTree> DBSportTrees
		{
			get
			{
				return this.GetTable<DBSportTree>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webAPI_Client_GetSportsTree")]
		public ISingleResult<DBSportTree> webAPI_Client_GetSportsTree([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="Char(2)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Duration", DbType="Int")] System.Nullable<int> duration, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BettingLineTemplateID", DbType="Int")] System.Nullable<int> bettingLineTemplateID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Day", DbType="DateTime")] System.Nullable<System.DateTime> day, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bias", DbType="Int")] System.Nullable<int> bias, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BetTypeGroupTemplateId", DbType="Int")] System.Nullable<int> betTypeGroupTemplateId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), languageCode, duration, bettingLineTemplateID, day, bias, betTypeGroupTemplateId);
			return ((ISingleResult<DBSportTree>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webAPI_Client_GetEventOdds")]
		public ISingleResult<webAPI_Client_GetEventOddsResult> webAPI_Client_GetEventOdds([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EventIds", DbType="VarChar(MAX)")] string eventIds, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="Char(2)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BetTypeGroupIds", DbType="VarChar(MAX)")] string betTypeGroupIds, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BettingLineTemplateID", DbType="Int")] System.Nullable<int> bettingLineTemplateID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="Int")] System.Nullable<int> type)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eventIds, languageCode, betTypeGroupIds, bettingLineTemplateID, type);
			return ((ISingleResult<webAPI_Client_GetEventOddsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.webAPI_Client_GetEventInfo")]
		public ISingleResult<webAPI_Client_GetEventInfoResult> webAPI_Client_GetEventInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LeagueIds", DbType="VarChar(MAX)")] string leagueIds, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EventIds", DbType="VarChar(MAX)")] string eventIds, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageCode", DbType="Char(2)")] string languageCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Day", DbType="DateTime")] System.Nullable<System.DateTime> day, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bias", DbType="Int")] System.Nullable<int> bias, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Duration", DbType="Int")] System.Nullable<int> duration, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BettingLineTemplateID", DbType="Int")] System.Nullable<int> bettingLineTemplateID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), leagueIds, eventIds, languageCode, day, bias, duration, bettingLineTemplateID);
			return ((ISingleResult<webAPI_Client_GetEventInfoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class DBSportTree
	{
		
		private int _LeagueId;
		
		private string _LeagueName;
		
		private string _CountryCode;
		
		private string _CountryName;
		
		private int _SportId;
		
		private string _ImageCode;
		
		private string _SportName;
		
		private int _EventCount;
		
		private string _BetTypeGroupName;
		
		private int _BetTypeGroupId;
		
		private int _BetTypeGroupOrdering;
		
		public DBSportTree()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeagueId", DbType="int")]
		public int LeagueId
		{
			get
			{
				return this._LeagueId;
			}
			set
			{
				if ((this._LeagueId != value))
				{
					this._LeagueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeagueName", DbType="nvarchar(50)", CanBeNull=false)]
		public string LeagueName
		{
			get
			{
				return this._LeagueName;
			}
			set
			{
				if ((this._LeagueName != value))
				{
					this._LeagueName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode", DbType="char(3)", CanBeNull=false)]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this._CountryCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryName", DbType="nvarchar(50)", CanBeNull=false)]
		public string CountryName
		{
			get
			{
				return this._CountryName;
			}
			set
			{
				if ((this._CountryName != value))
				{
					this._CountryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportId", DbType="int")]
		public int SportId
		{
			get
			{
				return this._SportId;
			}
			set
			{
				if ((this._SportId != value))
				{
					this._SportId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageCode", DbType="char(4)", CanBeNull=false)]
		public string ImageCode
		{
			get
			{
				return this._ImageCode;
			}
			set
			{
				if ((this._ImageCode != value))
				{
					this._ImageCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportName", DbType="nvarchar(50)", CanBeNull=false)]
		public string SportName
		{
			get
			{
				return this._SportName;
			}
			set
			{
				if ((this._SportName != value))
				{
					this._SportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventCount", DbType="int")]
		public int EventCount
		{
			get
			{
				return this._EventCount;
			}
			set
			{
				if ((this._EventCount != value))
				{
					this._EventCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BetTypeGroupName", DbType="nvarchar(50)", CanBeNull=false)]
		public string BetTypeGroupName
		{
			get
			{
				return this._BetTypeGroupName;
			}
			set
			{
				if ((this._BetTypeGroupName != value))
				{
					this._BetTypeGroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BetTypeGroupId", DbType="int")]
		public int BetTypeGroupId
		{
			get
			{
				return this._BetTypeGroupId;
			}
			set
			{
				if ((this._BetTypeGroupId != value))
				{
					this._BetTypeGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BetTypeGroupOrdering", DbType="int")]
		public int BetTypeGroupOrdering
		{
			get
			{
				return this._BetTypeGroupOrdering;
			}
			set
			{
				if ((this._BetTypeGroupOrdering != value))
				{
					this._BetTypeGroupOrdering = value;
				}
			}
		}
	}
	
	public partial class webAPI_Client_GetEventOddsResult
	{
		
		private int _Id;
		
		private int _EventId;
		
		private int _BetTypeId;
		
		private int _OddTypeId;
		
		private int _BetGroupId;
		
		private System.Nullable<double> _OddPoint;
		
		private System.Nullable<int> _TeamId;
		
		private double _OddFactor;
		
		private System.Nullable<short> _ColumnNumber;
		
		private int _SportId;
		
		public webAPI_Client_GetEventOddsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL")]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this._EventId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BetTypeId", DbType="Int NOT NULL")]
		public int BetTypeId
		{
			get
			{
				return this._BetTypeId;
			}
			set
			{
				if ((this._BetTypeId != value))
				{
					this._BetTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OddTypeId", DbType="Int NOT NULL")]
		public int OddTypeId
		{
			get
			{
				return this._OddTypeId;
			}
			set
			{
				if ((this._OddTypeId != value))
				{
					this._OddTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BetGroupId", DbType="Int NOT NULL")]
		public int BetGroupId
		{
			get
			{
				return this._BetGroupId;
			}
			set
			{
				if ((this._BetGroupId != value))
				{
					this._BetGroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OddPoint", DbType="Float")]
		public System.Nullable<double> OddPoint
		{
			get
			{
				return this._OddPoint;
			}
			set
			{
				if ((this._OddPoint != value))
				{
					this._OddPoint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamId", DbType="Int")]
		public System.Nullable<int> TeamId
		{
			get
			{
				return this._TeamId;
			}
			set
			{
				if ((this._TeamId != value))
				{
					this._TeamId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OddFactor", DbType="Float NOT NULL")]
		public double OddFactor
		{
			get
			{
				return this._OddFactor;
			}
			set
			{
				if ((this._OddFactor != value))
				{
					this._OddFactor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnNumber", DbType="SmallInt")]
		public System.Nullable<short> ColumnNumber
		{
			get
			{
				return this._ColumnNumber;
			}
			set
			{
				if ((this._ColumnNumber != value))
				{
					this._ColumnNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportId", DbType="Int NOT NULL")]
		public int SportId
		{
			get
			{
				return this._SportId;
			}
			set
			{
				if ((this._SportId != value))
				{
					this._SportId = value;
				}
			}
		}
	}
	
	public partial class webAPI_Client_GetEventInfoResult
	{
		
		private int _SportId;
		
		private string _SportName;
		
		private string _CountryCode;
		
		private string _CountryName;
		
		private int _LeagueId;
		
		private string _LeagueName;
		
		private int _EventID;
		
		private string _EventCode;
		
		private System.Nullable<int> _EventType;
		
		private string _EventName;
		
		private System.Nullable<System.DateTime> _EventDate;
		
		private System.Nullable<int> _Interval;
		
		private System.Nullable<int> _HomeId;
		
		private string _HomeName;
		
		private System.Nullable<int> _GuestId;
		
		private string _GuestName;
		
		public webAPI_Client_GetEventInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportId", DbType="Int NOT NULL")]
		public int SportId
		{
			get
			{
				return this._SportId;
			}
			set
			{
				if ((this._SportId != value))
				{
					this._SportId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SportName
		{
			get
			{
				return this._SportName;
			}
			set
			{
				if ((this._SportName != value))
				{
					this._SportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this._CountryCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CountryName
		{
			get
			{
				return this._CountryName;
			}
			set
			{
				if ((this._CountryName != value))
				{
					this._CountryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeagueId", DbType="Int NOT NULL")]
		public int LeagueId
		{
			get
			{
				return this._LeagueId;
			}
			set
			{
				if ((this._LeagueId != value))
				{
					this._LeagueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeagueName", DbType="NVarChar(50)")]
		public string LeagueName
		{
			get
			{
				return this._LeagueName;
			}
			set
			{
				if ((this._LeagueName != value))
				{
					this._LeagueName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventID", DbType="Int NOT NULL")]
		public int EventID
		{
			get
			{
				return this._EventID;
			}
			set
			{
				if ((this._EventID != value))
				{
					this._EventID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventCode", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string EventCode
		{
			get
			{
				return this._EventCode;
			}
			set
			{
				if ((this._EventCode != value))
				{
					this._EventCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventType", DbType="Int")]
		public System.Nullable<int> EventType
		{
			get
			{
				return this._EventType;
			}
			set
			{
				if ((this._EventType != value))
				{
					this._EventType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventName", DbType="NVarChar(200)")]
		public string EventName
		{
			get
			{
				return this._EventName;
			}
			set
			{
				if ((this._EventName != value))
				{
					this._EventName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EventDate
		{
			get
			{
				return this._EventDate;
			}
			set
			{
				if ((this._EventDate != value))
				{
					this._EventDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interval", DbType="Int")]
		public System.Nullable<int> Interval
		{
			get
			{
				return this._Interval;
			}
			set
			{
				if ((this._Interval != value))
				{
					this._Interval = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeId", DbType="Int")]
		public System.Nullable<int> HomeId
		{
			get
			{
				return this._HomeId;
			}
			set
			{
				if ((this._HomeId != value))
				{
					this._HomeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeName", DbType="NVarChar(50)")]
		public string HomeName
		{
			get
			{
				return this._HomeName;
			}
			set
			{
				if ((this._HomeName != value))
				{
					this._HomeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestId", DbType="Int")]
		public System.Nullable<int> GuestId
		{
			get
			{
				return this._GuestId;
			}
			set
			{
				if ((this._GuestId != value))
				{
					this._GuestId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestName", DbType="NVarChar(50)")]
		public string GuestName
		{
			get
			{
				return this._GuestName;
			}
			set
			{
				if ((this._GuestName != value))
				{
					this._GuestName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
